import Head from 'next/head';
import { Inter } from 'next/font/google';
// import Image from 'next/image';
import MyImage from '@/components/Image';
import ReactPlayer from 'react-player';
import { useState, useEffect, useRef, Fragment } from 'react';
import { Dialog, Transition } from '@headlessui/react';
import { ExclamationTriangleIcon } from '@heroicons/react/24/outline';
import axiosClient from '@/api/axiosClient';
import {
  FaPlus,
  FaRegImage,
  FaTimes,
  FaVideo,
  FaRegImages,
} from 'react-icons/fa';
import { toast } from 'react-toastify';
import Zoom from 'react-medium-image-zoom';
import 'react-medium-image-zoom/dist/styles.css';
import Link from 'next/link';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [hasWindow, setHasWindow] = useState(false);
  const [imageList, setImageList] = useState<any>([]);
  const [isLoad, setIsLoad] = useState(false);

  useEffect(() => {
    const getList = async () => {
      try {
        const res = await axiosClient.get('/api/post');
        setImageList(res);
      } catch (error) {
        console.log(error);
      }
    };
    getList();
  }, [isLoad]);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setHasWindow(true);
    }
  }, []);

  return (
    <div>
      <Head>
        {/* <title>Cum 💦💦</title> */}
        <title>Cum</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header isLoad={isLoad} setIsLoad={setIsLoad} />
        <div style={{ columnCount: '4', columnGap: '0px' }}>
          {hasWindow &&
            imageList?.map((item: any, index: any) =>
              item.type === 'image' ? (
                <div key={index} className='w-[100%]'>
                  <Zoom>
                    <img src={item.url} alt='c' className='h-auto' />
                  </Zoom>
                  {/* <FaTimes
                    className='absolute top-0 right-[0px] text-[20px] z-100 cursor-pointer'
                  /> */}
                </div>
              ) : (
                <div key={index} className=''>
                  <ReactPlayer
                    url={item.url}
                    width='auto'
                    height='auto'
                    playing={true}
                    muted={true}
                    controls={true}
                  />
                  {/* <FaTimes
                    className='absolute top-0 right-[0px] text-[20px] z-100 cursor-pointer'
                  /> */}
                </div>
              )
            )}
        </div>
      </main>
    </div>
  );
}
